twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        # the value is the service's id
        categoryRepository: '@App\Repository\CategoryRepository'

when@test:
    twig:
        strict_variables: true
